### PR TITLE
add shellcheck icon

### PR DESCRIPTION
**Pull request by bmalehorn**
Use the icon from the shellcheck website:

image

```
wget https://www.shellcheck.net/favicon.ico
convert favicon.ico shellcheck_icon.png
```

This will show up in the extension marketplace in place of the default icon:

image

### CODE REVIEW

**Comment by timonwong** [comment]
Hi,  @bmalehorn
Is there any legal problem with that logo?

**Comment by bmalehorn** [comment]
Closing this, can't get ahold of the author.

**Comment by koalaman** [comment]
My bad, I've been neglecting GitHub emails. Feel free to use it for whatever you want!

**Comment by bmalehorn** [comment]
Ah no worries, it's not exactly a life-or-death matter.

@timonwong I've reopened & rebased the pull request, should be safe to merge.

**Comment by timonwong** [comment]
Thanks :)

**Comment by brother** [comment]
@koalaman It would be great if the shellcheck.net repo had some licensing information attached.

https://github.com/koalaman/shellcheck.net

**Pull request merged**
