### PR TITLE
fix: shellcheck command failed

### LINKED ISSUE #144: Failed to run shellcheck: [null] Command failed
image

### PR DESCRIPTION
**Pull request by felipecrs**
Fixes #144

### CODE REVIEW

**Comment by felipecrs** [comment]
@PF4Public could you try with this version? You can download the `vsix` in the `release` job, under _Artifacts_.

**Comment by PF4Public** [comment]
I just tried and it works. Reloaded project a number of times, reopened vscode a number of times, but it still works without a flaw. Awesome!

**Comment by felipecrs** [comment]
This is amazing, I'm glad it worked. But I think the timeout is a bit too high, so I reverted to 2secs, could you please try again? I  prefer not to increase the timeout unless needed.

**Comment by PF4Public** [comment]
> I prefer not to increase the timeout unless needed.

I understand and share this concern.

Tested again, all is fine still. Just to be certain that extension was changed after reinstalling vsix, opened `extension.bundle.js` of the extension in editor:
image
Looks good.

**Comment by felipecrs** [comment]
Awesome!

**Pull request merged**
