### PR TITLE
chore: Use bundled binaries only on supported platforms

### PR DESCRIPTION
**Pull request by timonwong**

### CODE REVIEW

**Comment by felipecrs** [comment]
@timonwong we can easily bundle more binaries editing the `bindl.config.json`. Should we add more?

**Comment by timonwong** [comment]
@felipecrs I think it's OK now, 32bit and ARM precompiled binaries may be better since vscode officially supports them.

**Comment by felipecrs** [comment]
https://github.com/koalaman/shellcheck/releases/latest

I see the binary for ARM but not for 32bits though.

**Comment by felipecrs** [comment]
NVM, Windows binary is both x86 and x64. Linux and macOS only have x64 though.

**Comment by felipecrs** [comment]
May I push a commit in this branch?

**Comment by felipecrs** [comment]
@timonwong can you please merge https://github.com/timonwong/vscode-shellcheck/pull/103 in this branch and adjust the `linter.ts` to use the Windows binary on `x32` folder if arch == x32 or x64?

**Comment by timonwong** [comment]
@felipecrs thanks :) 
There is a huge mistake in my previous comment, that only windows requires ARM since it's officially supported.
Unfortunately, windows arm builds are missing for now, though I think it's ok due to the lack of userbase.

I'll exclude some binaries in the next PR, in order to mitigate the bloating size of our package :)

**Comment by timonwong** [comment]
@felipecrs Now v0.10.0 is released :)

**Comment by felipecrs** [comment]
@timonwong but how about Raspberry Pi users? They use VSCode, don't? I don't know.

**Comment by felipecrs** [comment]
> @felipecrs Now v0.10.0 is released :)

Awesome! :D

**Pull request merged**
