### PR TITLE
feat: add syntax highlight to `.shellcheckrc`

### PR DESCRIPTION
**Pull request by felipecrs**
Refs #350

### CODE REVIEW

**Comment by felipecrs** [comment]
@AaronHarris can you please check if this solves https://github.com/vscode-shellcheck/vscode-shellcheck/issues/350#issuecomment-937790302?

**Comment by koalaman** [comment]
> I don't know exactly what are all the things supported in the `.shellcheckrc` .

The general syntax is `key1=value1[,value2] [key2=value3...]` so you could potentially have something like:

```
enable=deprecate-which source-path=SCRIPTDIR disable=SC2016,SC2236
```

It probably should have been a standard file format, but for simplicity ShellCheck basically interpreted the `.shellcheckrc` file as if you copy-pasted it all with `# shellcheck` in front at the start of the script file, so it's more ad-hoc than it should have been.

**Comment by felipecrs** [comment]
I suppose `source-path` would accept paths, and in this case, the path could have spaces in it. How would it be handled?

**Comment by koalaman** [comment]
>How would it be handled?
Poorly :P

**Comment by felipecrs** [comment]
@koalaman, I think now it's good enough. What do you think?

image

**Comment by felipecrs** [comment]
Question: are inline comments supported?

**Pull request merged**
